namespace YourNamespace
{
	public class GlbStaff
	{
		public Guid GS_PK { get; set; }
		public string GS_LoginName { get; set; }
		public string GS_EmploymentBasis { get; set; }
		public string GS_NameTitle { get; set; }
		public string GS_NameSuffix { get; set; }
		public string GS_UserAddress2 { get; set; }
		public string GS_WorkPhone { get; set; }
		public string GS_WorkExtension { get; set; }
		public string GS_HomePhone { get; set; }
		public string GS_MobilePhone { get; set; }
		public string GS_Pager { get; set; }
		public string GS_FaxNum { get; set; }
		public string GS_Birthdate { get; set; }
		public string GS_WagesBankName { get; set; }
		public string GS_WagesBankAccount { get; set; }
		public string GS_WagesBankBsb { get; set; }
		public string GS_WagesBankSwift { get; set; }
		public string GS_NextOfKin { get; set; }
		public string GS_NextOfKinHomePhone { get; set; }
		public string GS_NextOfKinWorkPhone { get; set; }
		public string GS_EmergencyContactName { get; set; }
		public string GS_EmergencyHomePhone { get; set; }
		public string GS_EmergencyWorkPhone { get; set; }
		public DateTime GS_EmploymentDate { get; set; }
		public DateTime GS_DepartureDate { get; set; }
		public DateTime GS_DueBack { get; set; }
		public string GS_OutOnTask { get; set; }
		public string GS_PersonalEDIMailBox { get; set; }
		public string GS_BrokerID { get; set; }
		public string GS_BrokerPassword { get; set; }
		public string GS_BrokerWorkingPassword { get; set; }
		public string GS_Passport { get; set; }
		public DateTime GS_LastPasswordChangeDate { get; set; }
		public DateTime GS_NextReviewDate { get; set; }
		public Guid GS_GB_HomeBranch { get; set; }
		public Guid GS_GE_HomeDepartment { get; set; }
		public string GS_WorkingLanguage { get; set; }
		public string GS_ResourceType { get; set; }
		public string GS_SecurityCardNumber { get; set; }
		public string GS_EnterpriseCertificationID { get; set; }
		public DateTime GS_LastActivityDate { get; set; }
		public string GS_CommissionBasis { get; set; }
		public string GS_NextOfKinRelationship { get; set; }
		public string GS_EmergencyContactRelationship { get; set; }
		public DateTime GS_LastPasswordAttemptDateTime_Utc { get; set; }
		public string GS_Gender { get; set; }
		public bool GS_IsActivityLogged { get; set; }
		public Guid GS_ActiveDirectoryObjectGuid { get; set; }
		public DateTime GS_SystemCreateTimeUtc { get; set; }
		public string GS_SystemCreateUser { get; set; }
		public DateTime GS_SystemLastEditTimeUtc { get; set; }
		public string GS_SystemLastEditUser { get; set; }
		public bool GS_IsActive { get; set; }
		public bool GS_IsSalesRep { get; set; }
		public bool GS_IsController { get; set; }
		public bool GS_IsSystemAccount { get; set; }
		public bool GS_IsDeveloper { get; set; }
		public bool GS_PublishWorkPhone { get; set; }
		public bool GS_PublishWorkExtension { get; set; }
		public bool GS_PublishHomePhone { get; set; }
		public bool GS_PublishMobilePhone { get; set; }
		public bool GS_PublishFaxNum { get; set; }
		public bool GS_PublishEmailAddress { get; set; }
		public bool GS_EftWages { get; set; }
		public bool GS_IsInTrainingMode { get; set; }
		public bool GS_ChangePasswordAtNextLogin { get; set; }
		public bool GS_PasswordNeverChanges { get; set; }
		public bool GS_IsResource { get; set; }
		public bool GS_IsValid { get; set; }
		public string GS_EmailAddress { get; set; }
		public string GS_BrokerPasswordStatus { get; set; }
		public string GS_Code { get; set; }
		public string GS_FullName { get; set; }
		public string GS_UserAddress1 { get; set; }
		public string GS_State { get; set; }
		public string GS_Postcode { get; set; }
		public string GS_Title { get; set; }
		public string GS_FriendlyName { get; set; }
		public string GS_City { get; set; }
		public bool GS_IsOperational { get; set; }
		public Guid GS_GB_LastLogonBranch { get; set; }
		public Guid GS_GE_LastLogonDepartment { get; set; }
		public Guid GS_GC_PreferredPaymentCompany { get; set; }
		public bool GS_IsDevice { get; set; }
		public Guid GS_PER { get; set; }
		public string GS_RN_NKCountryCode { get; set; }
		public bool GS_IsTwoFactorAuthenticationEnabled { get; set; }
		public bool GS_CanLogin { get; set; }
		public string GS_AddressMap { get; set; }
		public string GS_ValidationStatus { get; set; }
		public string GS_RN_NKNationalityCode { get; set; }
		public string GS_DomainName { get; set; }
		public bool GS_IsDriver { get; set; }
		public string GS_ActivityTrackingStatus { get; set; }
		public int GS_PasswordHashIterations { get; set; }
		public string GS_EmergencyContactEmail { get; set; }
		public string GS_LastDayOfWork { get; set; }
		public string GS_NextOfKinEmail { get; set; }
		public string GS_ProbationEndDate { get; set; }
		public DateTime GS_ResidencyExpiry { get; set; }
		public string GS_ResidencyStatus { get; set; }
		public bool GS_SavePersonalDataToActiveDirectory { get; set; }
		public bool GS_IsRobot { get; set; }
		public string GS_ExternalId { get; set; }
		public string GS_FullNameInMotherLanguage { get; set; }
		public string GS_GivenName { get; set; }
		public string GS_MiddleName { get; set; }
		public string GS_PreferredSurname { get; set; }
		public string GS_Surname { get; set; }
		public string GS_GenderCustomTerm { get; set; }
		public byte[] GS_SqlLoginPasswordHash { get; set; }
		public byte[] GS_ActiveDirectorySid { get; set; }
		public string GS_SAMAccountFullName { get; set; }
		public string GS_SystemCreateBranch { get; set; }
		public string GS_SystemCreateDepartment { get; set; }
	}
}
