namespace YourNamespace
{
	public class JobShipment
	{
		public Guid JS_PK { get; set; }
		public string JS_ShipmentStatus { get; set; }
		public string JS_UniqueConsignRef { get; set; }
		public string JS_InterimReceipt { get; set; }
		public string JS_CartageWaybill { get; set; }
		public string JS_CFSReference { get; set; }
		public string JS_AWBServiceLevel { get; set; }
		public string JS_ConsolReference { get; set; }
		public string JS_HouseBill { get; set; }
		public string JS_BookingReference { get; set; }
		public DateTime JS_A_BKD { get; set; }
		public string JS_GoodsDescription { get; set; }
		public double JS_GoodsValue { get; set; }
		public int JS_PackingOrder { get; set; }
		public string JS_ReleaseType { get; set; }
		public Guid JS_OA_ExportReceivingDepot { get; set; }
		public Guid JS_OA_ImportReleaseDepot { get; set; }
		public Guid JS_OH_HandledOnBehalfOfForwarder { get; set; }
		public Guid JS_OH_TranshipAgent { get; set; }
		public Guid JS_OH_DeliveryAgent { get; set; }
		public DateTime JS_A_RCV { get; set; }
		public string JS_RL_NKOrigin { get; set; }
		public DateTime JS_E_DEP { get; set; }
		public string JS_RL_NKDestination { get; set; }
		public DateTime JS_E_ARV { get; set; }
		public DateTime JS_ClientRequestedETA { get; set; }
		public string JS_RS_NKServiceLevel { get; set; }
		public string JS_INCO { get; set; }
		public Guid JS_JX { get; set; }
		public string JS_TransportMode { get; set; }
		public string JS_PackingMode { get; set; }
		public double JS_ActualVolume { get; set; }
		public double JS_DocumentedVolume { get; set; }
		public double JS_ManifestedVolume { get; set; }
		public string JS_UnitOfVolume { get; set; }
		public double JS_ActualWeight { get; set; }
		public double JS_DocumentedWeight { get; set; }
		public double JS_ManifestedWeight { get; set; }
		public string JS_UnitOfWeight { get; set; }
		public double JS_ActualChargeable { get; set; }
		public double JS_DocumentedChargeable { get; set; }
		public double JS_ManifestedChargeable { get; set; }
		public double JS_UnitFreightRate { get; set; }
		public int JS_TotalPackageCount { get; set; }
		public int JS_OuterPacks { get; set; }
		public Guid JS_JS_ColoadMasterShipment { get; set; }
		public Guid JS_JS_SplitSwitchShipment { get; set; }
		public int JS_NoOriginalBills { get; set; }
		public int JS_NoCopyBills { get; set; }
		public Guid JS_OH_ExportBroker { get; set; }
		public string JS_HouseBillOfLadingType { get; set; }
		public string JS_ShippedOnBoard { get; set; }
		public DateTime JS_ShippedOnBoardDate { get; set; }
		public DateTime JS_HouseBillIssueDate { get; set; }
		public string JS_HBLAWBChargesDisplay { get; set; }
		public string JS_HBLContainerPackModeOverride { get; set; }
		public Guid JS_OH_ImportBroker { get; set; }
		public DateTime JS_SystemLastEditTimeUtc { get; set; }
		public string JS_SystemLastEditUser { get; set; }
		public DateTime JS_SystemCreateTimeUtc { get; set; }
		public string JS_SystemCreateUser { get; set; }
		public double JS_ShipperCODAmount { get; set; }
		public string JS_ShipperCODPayMethod { get; set; }
		public string JS_WarehouseLocation { get; set; }
		public Guid JS_WL { get; set; }
		public string JS_RX_NKGoodsValueCurr { get; set; }
		public double JS_InsuranceValue { get; set; }
		public string JS_RX_NKInsuranceCurrency { get; set; }
		public int JS_VisibleTabs { get; set; }
		public string JS_ShipmentType { get; set; }
		public string JS_RX_NKFrtRateCurrency { get; set; }
		public string JS_Phase { get; set; }
		public string JS_AdditionalTerms { get; set; }
		public string JS_F3_NKTotalCountPackType { get; set; }
		public string JS_F3_NKPackType { get; set; }
		public string JS_InvisibleTabsXML { get; set; }
		public double JS_LoadingMeters { get; set; }
		public double JS_DocumentedLoadingMeters { get; set; }
		public double JS_ManifestedLoadingMeters { get; set; }
		public string JS_FreightSpotRateAutoratingMode { get; set; }
		public double JS_FreightCostRate { get; set; }
		public string JS_RX_NKFreightCostRateCurrency { get; set; }
		public string JS_FreightCostRateAutoratingMode { get; set; }
		public double JS_GatewayFreightSellRate { get; set; }
		public string JS_RX_NKGatewayFreightSellRateCurrency { get; set; }
		public string JS_FreightGatewaySellRateAutoratingMode { get; set; }
		public bool JS_IsCancelled { get; set; }
		public bool JS_IsNeutralMaster { get; set; }
		public bool JS_IsShipping { get; set; }
		public bool JS_IsDirectBooking { get; set; }
		public bool JS_IsSplitShipment { get; set; }
		public bool JS_IsCFSRegistered { get; set; }
		public bool JS_IsForwardRegistered { get; set; }
		public bool JS_IsBooking { get; set; }
		public bool JS_TranshipToOtherCFS { get; set; }
		public bool JS_OverrideWaybillDefaults { get; set; }
		public bool JS_IsValid { get; set; }
		public bool JS_Legacy_Support_Columns_Start { get; set; }
		public string JS_RL_NKPlaceOfReceipt { get; set; }
		public string JS_RL_NKPlaceOfDischarge { get; set; }
		public string JS_EFreightStatus { get; set; }
		public string JS_RL_NKHouseBillIssuePlace { get; set; }
		public DateTime JS_AttachedOrderXMLUpdateCutOffDateUtc { get; set; }
		public Guid JS_TH_OneTimeQuote { get; set; }
		public string JS_RL_NKDischargePort { get; set; }
		public string JS_RL_NKFreightRateDestination { get; set; }
		public string JS_RL_NKFreightRateOrigin { get; set; }
		public string JS_RL_NKLoadPort { get; set; }
		public string JS_ScreeningStatus { get; set; }
		public bool JS_IsHighRisk { get; set; }
		public string JS_PaymentTermAutoratingOverride { get; set; }
		public string JS_PL_NKCarrierServiceLevel { get; set; }
		public DateTime JS_ExportReceivingDepotDispatchRequested { get; set; }
		public DateTime JS_ExportReceivingDepotReceiptRequested { get; set; }
		public DateTime JS_ImportReleaseDepotDispatchRequested { get; set; }
		public DateTime JS_ImportReleaseDepotReceiptRequested { get; set; }
		public string JS_CommunityTransitStatus { get; set; }
		public Guid JS_OA_BookedShippingLineAddress { get; set; }
		public string JS_BookedVesselScreeningStatus { get; set; }
		public string JS_CarrierContractNumber { get; set; }
		public Guid JS_RCA_BookingAllocationLine { get; set; }
		public int JS_CompanyTariffLevelOverride { get; set; }
		public string JS_FMCTariffID { get; set; }
		public DateTimeOffset JS_RevisedDeliveryDueDate { get; set; }
		public string JS_RH_NKRateCommodity { get; set; }
		public Guid JS_OH_Creditor { get; set; }
		public string JS_RS_NKGatewayServiceLevel { get; set; }
		public string JS_ElectronicBillOfLadingReference { get; set; }
		public string JS_ElectronicBillOfLadingStatus { get; set; }
		public string JS_ElectronicBillOfLadingTerms { get; set; }
		public string JS_ElectronicBillOfLadingType { get; set; }
		public int JS_ElectronicBillOfLadingVersion { get; set; }
		public string JS_ElectronicBillOfLadingHouseBill { get; set; }
		public string JS_SystemCreateBranch { get; set; }
		public string JS_SystemCreateDepartment { get; set; }
		public Guid JS_RTT_TransitTime { get; set; }
		public DateTimeOffset JS_DeliveryDueDate { get; set; }
		public bool JS_IsBookingAgentShipment { get; set; }
	}
}
